language: python
python:
  - "3.7"
sudo: required
services:
  - docker

before_install: 
  #- pip install --upgrade pip
  #- pip install -r requirements.txt
  - docker build -t kakazhang/django .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
script: true
